SELECT PLAN_ORDER_DESCRIPTION.ORDER_VERSION, PLAN_ORDER_DESCRIPTION.ORDER_LABEL, PLAN_ORDER_DESCRIPTION.ORDER_ID, PLAN_ORDER_DESCRIPTION.PATH_ID, PLAN_ORDER_DESCRIPTION.BOM_ID, PLAN_ORDER_DESCRIPTION.ROUTE_ID, PLAN_ORDER_DESCRIPTION.PRIME_LOCATION, PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME, PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME, PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE, PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS, PLAN_ORDER_DESCRIPTION.UPDATE_CODE, PLAN_ORDER_DESCRIPTION.ORDER_STATUS, PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS, PLAN_ORDER_DESCRIPTION.OFFLOAD, PLAN_ORDER_DESCRIPTION.PROD_ORDER, PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND, PLAN_ORDER_DESCRIPTION.ENFORCEMENT, PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE, PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE, PLAN_ORDER_DESCRIPTION.PARENT_ORDER, PLAN_ORDER_DESCRIPTION.SUPER_ORDER, PLAN_ORDER_DESCRIPTION.PLANNER_CODE, PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY, PLAN_ORDER_DESCRIPTION.PARENT_COUPLING, PLAN_ORDER_DESCRIPTION.SKU, PLAN_ORDER_DESCRIPTION.LOCATION, PLAN_ORDER_DESCRIPTION.FAMILY, PLAN_ORDER_DESCRIPTION.STYLE, PLAN_ORDER_DESCRIPTION.COLOR, PLAN_ORDER_DESCRIPTION.ATTRIBUTE, PLAN_ORDER_DESCRIPTION.ORDER_SIZE, PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY, PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY, PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY, PLAN_ORDER_DESCRIPTION.DEMAND_TYPE, PLAN_ORDER_DESCRIPTION.WINDOW_START, PLAN_ORDER_DESCRIPTION.WINDOW_END, PLAN_ORDER_DESCRIPTION.SCHEDULED_START, PLAN_ORDER_DESCRIPTION.SCHEDULED_END, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END, PLAN_ORDER_DESCRIPTION.PRIORITY, PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR, PLAN_ORDER_DESCRIPTION.NOTE, PLAN_ORDER_DESCRIPTION.VENDOR_NO, PLAN_ORDER_DESCRIPTION.SCRAP_QTY, PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY, PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY, PLAN_ORDER_DESCRIPTION.ATP_DATE_IND, PLAN_ORDER_DESCRIPTION.BACKFILL_IND, PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD, PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO, PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD, PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD, PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD, PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD, PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO, PLAN_ORDER_DESCRIPTION.SELLING_SKU, PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD, PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN, PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO, PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC, PLAN_ORDER_DESCRIPTION.LW_COMPANY, PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
SCHEDULED_START / 1440 + 33231 AS "SewWeek",
SCHEDULED_END / 1440 + 33231 AS "DCWeek", ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC
FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW, AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD AND plan_order_description.SEW_ALLOC = 'WM_G20' AND plan_order_description.prime_location = '93' 

SELECT *
FROM DELSPIN_MPS_LATENESS_RESULTS Del

SELECT *
FROM da.ITEM_SIZE is2 

SELECT 
    PLAN_ORDER_DESCRIPTION.ORDER_VERSION,
    PLAN_ORDER_DESCRIPTION.ORDER_LABEL,
    PLAN_ORDER_DESCRIPTION.ORDER_ID,
    PLAN_ORDER_DESCRIPTION.PATH_ID,
    PLAN_ORDER_DESCRIPTION.BOM_ID,
    PLAN_ORDER_DESCRIPTION.ROUTE_ID,
    PLAN_ORDER_DESCRIPTION.PRIME_LOCATION,
    PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME,
    PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME,
    PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE,
    PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS,
    PLAN_ORDER_DESCRIPTION.UPDATE_CODE,
    PLAN_ORDER_DESCRIPTION.ORDER_STATUS,
    PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS,
    PLAN_ORDER_DESCRIPTION.OFFLOAD,
    PLAN_ORDER_DESCRIPTION.PROD_ORDER,
    PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND,
    PLAN_ORDER_DESCRIPTION.ENFORCEMENT,
    PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE,
    PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE,
    PLAN_ORDER_DESCRIPTION.PARENT_ORDER,
    PLAN_ORDER_DESCRIPTION.SUPER_ORDER,
    PLAN_ORDER_DESCRIPTION.PLANNER_CODE,
    PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY,
    PLAN_ORDER_DESCRIPTION.PARENT_COUPLING,
    PLAN_ORDER_DESCRIPTION.SKU,
    PLAN_ORDER_DESCRIPTION.LOCATION,
    PLAN_ORDER_DESCRIPTION.FAMILY,
    PLAN_ORDER_DESCRIPTION.STYLE,
    PLAN_ORDER_DESCRIPTION.COLOR,
    PLAN_ORDER_DESCRIPTION.ATTRIBUTE,
    PLAN_ORDER_DESCRIPTION.ORDER_SIZE,
    PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY,
    PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY,
    PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY,
    PLAN_ORDER_DESCRIPTION.DEMAND_TYPE,
    PLAN_ORDER_DESCRIPTION.WINDOW_START,
    PLAN_ORDER_DESCRIPTION.WINDOW_END,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_START,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_END,
    PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START,
    PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END,
    PLAN_ORDER_DESCRIPTION.PRIORITY,
    PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR,
    PLAN_ORDER_DESCRIPTION.NOTE,
    PLAN_ORDER_DESCRIPTION.VENDOR_NO,
    PLAN_ORDER_DESCRIPTION.SCRAP_QTY,
    PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY,
    PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY,
    PLAN_ORDER_DESCRIPTION.ATP_DATE_IND,
    PLAN_ORDER_DESCRIPTION.BACKFILL_IND,
    PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD,
    PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO,
    PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD,
    PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO,
    PLAN_ORDER_DESCRIPTION.SELLING_SKU,
    PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD,
    PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN,
    PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO,
    PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC,
    PLAN_ORDER_DESCRIPTION.LW_COMPANY,
    PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
    SCHEDULED_START / 1440 + 33231 AS "SewWeek",
    SCHEDULED_END / 1440 + 33231 AS "DCWeek",
    ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC,
    ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC,
    ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC
FROM 
    OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW,
    AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE 
    PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD
    AND ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC IN (
        'TKS_A3', 'TKS_HU', 'TKS_IA', 'TKS_S8', 'TKS_Z0', 'TKSBRA_BR', 'TKSBRA_M8',
        'TKSBRA_WB', 'TKSCW_M8', 'TKSPTY_M8', 'TKSPTY_WB', 'TKSSHP_BR', 'TKSSHP_M8',
        'TKSSM_M8', 'CAN_PTYTKS', 'CANBRATKS', 'TKS_6Z', 'TKS_AL', 'TKS_E5', 'TKS_F6',
        'TKS_LD', 'TKS_ZC', 'TKSHSCI_PT', 'TKS_1B', 'TKS_PV', 'TKS_Z4'
    );

--- CHECK ALL FIELD   
   
SELECT *
FROM AVYX.PLAN_ORDER_DESCRIPTION


   
   --- Another one
   
   SELECT 
    PLAN_ORDER_DESCRIPTION.ORDER_VERSION,
    PLAN_ORDER_DESCRIPTION.ORDER_LABEL,
    PLAN_ORDER_DESCRIPTION.ORDER_ID,
    PLAN_ORDER_DESCRIPTION.PATH_ID,
    PLAN_ORDER_DESCRIPTION.BOM_ID,
    PLAN_ORDER_DESCRIPTION.ROUTE_ID,
    PLAN_ORDER_DESCRIPTION.PRIME_LOCATION,
    PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME,
    PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME,
    PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE,
    PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS,
    PLAN_ORDER_DESCRIPTION.UPDATE_CODE,
    PLAN_ORDER_DESCRIPTION.ORDER_STATUS,
    PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS,
    PLAN_ORDER_DESCRIPTION.OFFLOAD,
    PLAN_ORDER_DESCRIPTION.PROD_ORDER,
    PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND,
    PLAN_ORDER_DESCRIPTION.ENFORCEMENT,
    PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE,
    PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE,
    PLAN_ORDER_DESCRIPTION.PARENT_ORDER,
    PLAN_ORDER_DESCRIPTION.SUPER_ORDER,
    PLAN_ORDER_DESCRIPTION.PLANNER_CODE,
    PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY,
    PLAN_ORDER_DESCRIPTION.PARENT_COUPLING,
    PLAN_ORDER_DESCRIPTION.SKU,
    PLAN_ORDER_DESCRIPTION.LOCATION,
    PLAN_ORDER_DESCRIPTION.FAMILY,
    PLAN_ORDER_DESCRIPTION.STYLE,
    PLAN_ORDER_DESCRIPTION.COLOR,
    PLAN_ORDER_DESCRIPTION.ATTRIBUTE,
    PLAN_ORDER_DESCRIPTION.ORDER_SIZE,
    PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY,
    PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY,
    PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY,
    PLAN_ORDER_DESCRIPTION.DEMAND_TYPE,
    PLAN_ORDER_DESCRIPTION.WINDOW_START,
    PLAN_ORDER_DESCRIPTION.WINDOW_END,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_START,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_END,
    PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START,
    PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END,
    PLAN_ORDER_DESCRIPTION.PRIORITY,
    PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR,
    PLAN_ORDER_DESCRIPTION.NOTE,
    PLAN_ORDER_DESCRIPTION.VENDOR_NO,
    PLAN_ORDER_DESCRIPTION.SCRAP_QTY,
    PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY,
    PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY,
    PLAN_ORDER_DESCRIPTION.ATP_DATE_IND,
    PLAN_ORDER_DESCRIPTION.BACKFILL_IND,
    PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD,
    PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO,
    PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD,
    PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO,
    PLAN_ORDER_DESCRIPTION.SELLING_SKU,
    PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD,
    PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN,
    PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO,
    PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC,
    PLAN_ORDER_DESCRIPTION.LW_COMPANY,
    PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
    SCHEDULED_START / 1440 + 33231 AS "SewWeek",
    SCHEDULED_END / 1440 + 33231 AS "DCWeek",
    ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC,
    ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC,
    ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC
FROM 
    OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW,
    AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE 
    PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD
    AND PLAN_ORDER_DESCRIPTION.STYLE = 'DMSMLB';

   
SELECT
    PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_START,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_END,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_START / 1440 + 33231 AS "SewWeek",
    PLAN_ORDER_DESCRIPTION.SCHEDULED_END / 1440 + 33231 AS "DCWeek"
FROM AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = 'MHG521';


 --- Another one Taking SEW START, END and DC from ISS_PROD_SUMMARY
SELECT  
    pod.ORDER_VERSION,
    pod.ORDER_LABEL,
    pod.ORDER_ID,
    pod.PATH_ID,
    pod.BOM_ID,
    pod.ROUTE_ID,
    pod.PRIME_LOCATION,
    pod.LOCK_LEAD_TIME,
    pod.RELEASE_LEAD_TIME,
    pod.MAKE_BUY_CODE,
    pod.PRODUCTION_STATUS,
    pod.UPDATE_CODE,
    pod.ORDER_STATUS,
    pod.ACTUALS_STATUS,
    pod.OFFLOAD,
    pod.PROD_ORDER,
    pod.PROD_ORDER_IND,
    pod.ENFORCEMENT,
    pod.ALLOCATION_OVERRIDE,
    pod.MATERIAL_TYPE,
    pod.PARENT_ORDER,
    pod.SUPER_ORDER,
    pod.PLANNER_CODE,
    pod.PARENT_ACTIVITY,
    pod.PARENT_COUPLING,
    pod.SKU,
    pod.LOCATION,
    pod.FAMILY,
    pod.STYLE,
    pod.COLOR,
    pod.ATTRIBUTE,
    pod.ORDER_SIZE,
    pod.REMAINING_QUANTITY,
    pod.PARITIAL_QUANTITY,
    pod.ORIG_QUANTITY,
    pod.DEMAND_TYPE,
    pod.WINDOW_START,
    pod.WINDOW_END,
    pod.SCHEDULED_START,
    pod.SCHEDULED_END,
    pod.ORIG_SCHEDULED_START,
    pod.ORIG_SCHEDULED_END,
    pod.PRIORITY,
    pod.SCRAP_FACTOR,
    pod.NOTE,
    pod.VENDOR_NO,
    pod.SCRAP_QTY,
    pod.NET_ORDER_QTY,
    pod.CURR_ORDER_QTY,
    pod.ATP_DATE_IND,
    pod.BACKFILL_IND,
    pod.ORDER_SOURCE_CD,
    pod.ISS_ORDER_NO,
    pod.SELLING_STYLE_CD,
    pod.SELLING_COLOR_CD,
    pod.SELLING_ATTRIBUTE_CD,
    pod.SELLING_SIZE_CD,
    pod.MFG_REVISION_NO,
    pod.SELLING_SKU,
    pod.SCHEDULE_METHOD,
    pod.SCHEDULE_RUN,
    pod.LW_VENDOR_NO,
    pod.LW_VENDOR_LOC,
    pod.LW_COMPANY,
    pod.ADEXA_PLAN_DATE,

    pod.SCHEDULED_START / 1440 + 33231 AS SewWeek,
    pod.SCHEDULED_END   / 1440 + 33231 AS DCWeek,

    alloc.CUT_ALLOC,
    alloc.SEW_ALLOC,
    alloc.SRC_ALLOC,

    -- Fields from ISS_PROD_SUMMARY (NULL if no match)
    ips.SEW_START_DATE,
    ips.SEW_DUE_DATE,
    ips.CURR_DUE_DATE

FROM AVYX.PLAN_ORDER_DESCRIPTION pod

JOIN OPRSQL.ISS_CAP_ALLOC_XREF_VIEW alloc
    ON pod.SELLING_STYLE_CD = alloc.STYLE_CD

LEFT JOIN da.ISS_PROD_SUMMARY ips
    ON pod.SUPER_ORDER = ips.SUPER_ORDER  -- will return NULLs if no match

WHERE pod.STYLE = 'DMSMLB';


--- to take only first sew week each SKU
--- with sew allocation filter

SELECT 
    t.SKU,
    t.LOCATION,
    t.FAMILY,
    t.STYLE,
    t.COLOR,
    t.ATTRIBUTE,
    t.SELLING_STYLE_CD,
    t.SELLING_COLOR_CD,
    t.SELLING_ATTRIBUTE_CD,
    t.SELLING_SIZE_CD,

    t.SewWeek,
    MIN(t.DCWeek) AS DCWeek,

    SUM(t.ORIG_QUANTITY)      AS TOTAL_ORIG_QUANTITY,
    SUM(t.REMAINING_QUANTITY) AS TOTAL_REMAINING_QUANTITY,
    SUM(t.PARITIAL_QUANTITY)  AS TOTAL_PARTIAL_QUANTITY,
    SUM(t.NET_ORDER_QTY)      AS TOTAL_NET_ORDER_QTY,
    SUM(t.CURR_ORDER_QTY)     AS TOTAL_CURR_ORDER_QTY,
    SUM(t.SCRAP_QTY)          AS TOTAL_SCRAP_QTY,

    MAX(t.CUT_ALLOC) AS CUT_ALLOC,
    MAX(t.SEW_ALLOC) AS SEW_ALLOC,
    MAX(t.SRC_ALLOC) AS SRC_ALLOC

FROM (
    SELECT 
        p.SKU,
        p.LOCATION,
        p.FAMILY,
        p.STYLE,
        p.COLOR,
        p.ATTRIBUTE,
        p.SELLING_STYLE_CD,
        p.SELLING_COLOR_CD,
        p.SELLING_ATTRIBUTE_CD,
        p.SELLING_SIZE_CD,

        p.ORIG_QUANTITY,
        p.REMAINING_QUANTITY,
        p.PARITIAL_QUANTITY,
        p.NET_ORDER_QTY,
        p.CURR_ORDER_QTY,
        p.SCRAP_QTY,

        (p.SCHEDULED_START / 1440 + 33231) AS SewWeek,
        (p.SCHEDULED_END   / 1440 + 33231) AS DCWeek,

        x.CUT_ALLOC,
        x.SEW_ALLOC,
        x.SRC_ALLOC,

        MIN(p.SCHEDULED_START / 1440 + 33231)
            OVER (PARTITION BY p.SKU) AS Min_SewWeek

    FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW x
    JOIN AVYX.PLAN_ORDER_DESCRIPTION p
        ON p.SELLING_STYLE_CD = x.STYLE_CD

    WHERE x.SEW_ALLOC IN (
        'TKS_A3','TKS_HU','TKS_IA','TKS_S8','TKS_Z0','TKSBRA_BR','TKSBRA_M8',
        'TKSBRA_WB','TKSCW_M8','TKSPTY_M8','TKSPTY_WB','TKSSHP_BR','TKSSHP_M8',
        'TKSSM_M8','CAN_PTYTKS','CANBRATKS','TKS_6Z','TKS_AL','TKS_E5','TKS_F6',
        'TKS_LD','TKS_ZC','TKSHSCI_PT','TKS_1B','TKS_PV','TKS_Z4','BOY_G20','MEN_G20'
    )
) t

WHERE t.SewWeek = t.Min_SewWeek

GROUP BY 
    t.SKU,
    t.LOCATION,
    t.FAMILY,
    t.STYLE,
    t.COLOR,
    t.ATTRIBUTE,
    t.SELLING_STYLE_CD,
    t.SELLING_COLOR_CD,
    t.SELLING_ATTRIBUTE_CD,
    t.SELLING_SIZE_CD,
    t.SewWeek;

--- without sew allocation filter
   
SELECT 
    t.SKU,
    t.LOCATION,
    t.FAMILY,
    t.STYLE,
    t.COLOR,
    t.ATTRIBUTE,
    t.SELLING_STYLE_CD,
    t.SELLING_COLOR_CD,
    t.SELLING_ATTRIBUTE_CD,
    t.SELLING_SIZE_CD,

    t.SewWeek,
    MIN(t.DCWeek) AS DCWeek,

    SUM(t.ORIG_QUANTITY)      / 12 AS TOTAL_ORIG_DOZ,
    SUM(t.REMAINING_QUANTITY) / 12 AS TOTAL_REMAINING_DOZ,
    SUM(t.PARITIAL_QUANTITY)  / 12 AS TOTAL_PARTIAL_DOZ,
    SUM(t.NET_ORDER_QTY)      / 12 AS TOTAL_NET_ORDER_DOZ,
    SUM(t.CURR_ORDER_QTY)     / 12 AS TOTAL_CURR_ORDER_DOZ,
    SUM(t.SCRAP_QTY)          / 12 AS TOTAL_SCRAP_DOZ,

    MAX(t.CUT_ALLOC) AS CUT_ALLOC,
    MAX(t.SEW_ALLOC) AS SEW_ALLOC,
    MAX(t.SRC_ALLOC) AS SRC_ALLOC

FROM (
    SELECT 
        p.SKU,
        p.LOCATION,
        p.FAMILY,
        p.STYLE,
        p.COLOR,
        p.ATTRIBUTE,
        p.SELLING_STYLE_CD,
        p.SELLING_COLOR_CD,
        p.SELLING_ATTRIBUTE_CD,
        p.SELLING_SIZE_CD,

        p.ORIG_QUANTITY,
        p.REMAINING_QUANTITY,
        p.PARITIAL_QUANTITY,
        p.NET_ORDER_QTY,
        p.CURR_ORDER_QTY,
        p.SCRAP_QTY,

        (p.SCHEDULED_START / 1440 + 33231) AS SewWeek,
        (p.SCHEDULED_END   / 1440 + 33231) AS DCWeek,

        x.CUT_ALLOC,
        x.SEW_ALLOC,
        x.SRC_ALLOC,

        MIN(p.SCHEDULED_START / 1440 + 33231)
            OVER (PARTITION BY p.SKU) AS Min_SewWeek

    FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW x
    JOIN AVYX.PLAN_ORDER_DESCRIPTION p
        ON p.SELLING_STYLE_CD = x.STYLE_CD

) t

WHERE t.SewWeek = t.Min_SewWeek

GROUP BY 
    t.SKU,
    t.LOCATION,
    t.FAMILY,
    t.STYLE,
    t.COLOR,
    t.ATTRIBUTE,
    t.SELLING_STYLE_CD,
    t.SELLING_COLOR_CD,
    t.SELLING_ATTRIBUTE_CD,
    t.SELLING_SIZE_CD,
    t.SewWeek;

   
-- working temp

SELECT *
FROM da.ITEM_SIZE is2 
   
SELECT
    PLAN_ORDER_DESCRIPTION.ORDER_VERSION,
    PLAN_ORDER_DESCRIPTION.ORDER_LABEL,
    PLAN_ORDER_DESCRIPTION.ORDER_ID,
    PLAN_ORDER_DESCRIPTION.PATH_ID,
    PLAN_ORDER_DESCRIPTION.BOM_ID,
    PLAN_ORDER_DESCRIPTION.ROUTE_ID,
    PLAN_ORDER_DESCRIPTION.PRIME_LOCATION,
    PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME,
    PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME,
    PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE,
    PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS,
    PLAN_ORDER_DESCRIPTION.UPDATE_CODE,
    PLAN_ORDER_DESCRIPTION.ORDER_STATUS,
    PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS,
    PLAN_ORDER_DESCRIPTION.OFFLOAD,
    PLAN_ORDER_DESCRIPTION.PROD_ORDER,
    PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND,
    PLAN_ORDER_DESCRIPTION.ENFORCEMENT,
    PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE,
    PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE,
    PLAN_ORDER_DESCRIPTION.PARENT_ORDER,
    PLAN_ORDER_DESCRIPTION.SUPER_ORDER,
    PLAN_ORDER_DESCRIPTION.PLANNER_CODE,
    PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY,
    PLAN_ORDER_DESCRIPTION.PARENT_COUPLING,
    PLAN_ORDER_DESCRIPTION.SKU,
    PLAN_ORDER_DESCRIPTION.LOCATION,
    PLAN_ORDER_DESCRIPTION.FAMILY,
    PLAN_ORDER_DESCRIPTION.STYLE,
    PLAN_ORDER_DESCRIPTION.COLOR,
    PLAN_ORDER_DESCRIPTION.ATTRIBUTE,
    PLAN_ORDER_DESCRIPTION.ORDER_SIZE,
    PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY,
    PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY,
    PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY,
    PLAN_ORDER_DESCRIPTION.DEMAND_TYPE,
    PLAN_ORDER_DESCRIPTION.WINDOW_START,
    PLAN_ORDER_DESCRIPTION.WINDOW_END,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_START,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_END,
    PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START,
    PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END,
    PLAN_ORDER_DESCRIPTION.PRIORITY,
    PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR,
    PLAN_ORDER_DESCRIPTION.NOTE,
    PLAN_ORDER_DESCRIPTION.VENDOR_NO,
    PLAN_ORDER_DESCRIPTION.SCRAP_QTY,
    PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY,
    PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY,
    PLAN_ORDER_DESCRIPTION.ATP_DATE_IND,
    PLAN_ORDER_DESCRIPTION.BACKFILL_IND,
    PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD,
    PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO,
    PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD,
    PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD,
    PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO,
    PLAN_ORDER_DESCRIPTION.SELLING_SKU,
    PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD,
    PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN,
    PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO,
    PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC,
    PLAN_ORDER_DESCRIPTION.LW_COMPANY,
    PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
    PLAN_ORDER_DESCRIPTION.SCHEDULED_START / 1440 + 33231 AS "SewWeek",
    PLAN_ORDER_DESCRIPTION.SCHEDULED_END   / 1440 + 33231 AS "DCWeek",
    ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC,
    ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC,
    ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC,
    ITEM_SIZE.SIZE_SHORT_DESC              AS SIZE_SHORT_DESC  -- ✅ a
FROM
    AVYX.PLAN_ORDER_DESCRIPTION          PLAN_ORDER_DESCRIPTION
    JOIN OPRSQL.ISS_CAP_ALLOC_XREF_VIEW  ISS_CAP_ALLOC_XREF_VIEW
        ON PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD
    LEFT JOIN DA.ITEM_SIZE               ITEM_SIZE              -- ✅ updated
        ON PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD  = ITEM_SIZE.SIZE_CD

    WHERE
    ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC = 'TKSBRA_M8'
    
    WHERE
    ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC IN (
        'TKS_A3', 'TKS_HU', 'TKS_IA', 'TKS_S8', 'TKS_Z0', 'TKSBRA_BR', 'TKSBRA_M8',
        'TKSBRA_WB', 'TKSCW_M8', 'TKSPTY_M8', 'TKSPTY_WB', 'TKSSHP_BR', 'TKSSHP_M8',
        'TKSSM_M8', 'CAN_PTYTKS', 'CANBRATKS', 'TKS_6Z', 'TKS_AL', 'TKS_E5', 'TKS_F6',
        'TKS_LD', 'TKS_ZC', 'TKSHSCI_PT', 'TKS_1B', 'TKS_PV', 'TKS_Z4'
    );


   
   
   