SELECT DPR_CUMULATIVE_LEADTIME.CORP_BUSINESS_UNIT, DPR_CUMULATIVE_LEADTIME.STYLE_CD, DPR_CUMULATIVE_LEADTIME.COLOR_CD, DPR_CUMULATIVE_LEADTIME.CUMULATIVE_LEADTIME, DPR_CUMULATIVE_LEADTIME.RECEIPT_PERIOD, DPR_CUMULATIVE_LEADTIME.USER_ID, DPR_CUMULATIVE_LEADTIME.CREATE_DATE, DPR_CUMULATIVE_LEADTIME.UPDATE_DATE
FROM DA.DPR_CUMULATIVE_LEADTIME DPR_CUMULATIVE_LEADTIME
WHERE

'DPR CUM'

SELECT *
FROM DA.DPR_CUMULATIVE_LEADTIME DPRCum
WHERE STYLE_cd like 'PW43AS'

SELECT *
FROM DA.DPR_DIRECT_SHIP dds 


SELECT *
FROM DA.DPR_CUMULATIVE_LEADTIME DPRCum
WHERE STYLE_cd in ('DA3820','DF3385','DFMLH3') AND COLOR_CD in ('CKU','ZGZ')

'Selling Ratio'
SELECT R.*
FROM DA.SELLING_STYLE_RATIO R, (SELECT SELLING_STYLE_CD, MAX(BEGIN_EFFECT_DATE) AS "BEGIN_EFFECT_DATE" FROM DA.SELLING_STYLE_RATIO GROUP BY SELLING_STYLE_CD) E
WHERE R.SELLING_STYLE_CD = E.SELLING_STYLE_CD AND R.BEGIN_EFFECT_DATE = E.BEGIN_EFFECT_DATE

SELECT *
FROM DA.SELLING_STYLE_RATIO R
WHERE SELLING_STYLE_CD in ('2349C4','7460P4','MKCBX5')

'Path Ranking'
SELECT PATH_RANKING.STYLE, PATH_RANKING.COLOR, PATH_RANKING.ATTRIBUTE_CD, PATH_RANKING.SIZE_CD, PATH_RANKING.DEMAND_LOC, PATH_RANKING.MFG_PATH_ID, PATH_RANKING.MFG_STYLE_CD, PATH_RANKING.MFG_COLOR_CD, PATH_RANKING.MFG_ATTRIBUTE_CD, PATH_RANKING.MFG_SIZE_CD, PATH_RANKING.PATH_RANKING_NO, PATH_RANKING.CREATE_DATE, PATH_RANKING.UPDATE_DATE, PATH_RANKING.USER_ID, PATH_RANKING.CUT_PART_PATH_ID, PATH_RANKING.FINISHED_FABRIC_PATH_ID, PATH_RANKING.GREIGE_CLOTH_PATH_ID, PATH_RANKING.REVISION_NO
FROM DA.PATH_RANKING PATH_RANKING

'Path Ranking'
SELECT * 
FROM DA.STYLE STY
WHERE PLAN_STATUS_CD = 'A' AND primary_DC IN ('KM','KG','PW','J1','VI','3M')

SELECT * 
FROM DA.PATH_RANKING pr 
WHERE MFG_PATH_ID = '93'
WHERE STYLE = 'MRH405'

SELECT DISTINCT t.style, t.color,t.PATH_RANKING_NO 
FROM DA.PATH_RANKING t
WHERE NOT EXISTS (
    SELECT 1
    FROM DA.PATH_RANKING x
    WHERE x.style = t.style
      AND x.color = t.color
      AND x.path_ranking_no = 5
);

SELECT DISTINCT t.style, t.color, t.PATH_RANKING_NO
FROM DA.PATH_RANKING t
WHERE EXISTS (
    SELECT 1
    FROM DA.PATH_RANKING x
    WHERE x.style = t.style
      AND x.color = t.color
      AND x.path_ranking_no = 5
);


'Transportation Lead time'
SELECT TRANSPORTATION.FROM_PLANT_CD, TRANSPORTATION.TO_PLANT_CD, TRANSPORTATION.DAYS_IN_TRANSIT, TRANSPORTATION.USER_ID, TRANSPORTATION.CREATE_DATE, TRANSPORTATION.UPDATE_DATE, TRANSPORTATION.MRP_DAYS_IT
FROM DA.TRANSPORTATION TRANSPORTATION
WHERE transportation.TO_PLANT_CD = 'PW' AND transportation.FROM_PLANT_CD = '95'

SELECT TRANSPORTATION.FROM_PLANT_CD, TRANSPORTATION.TO_PLANT_CD, TRANSPORTATION.DAYS_IN_TRANSIT, TRANSPORTATION.USER_ID, TRANSPORTATION.CREATE_DATE, TRANSPORTATION.UPDATE_DATE, TRANSPORTATION.MRP_DAYS_IT
FROM DA.TRANSPORTATION TRANSPORTATION
WHERE transportation.FROM_PLANT_CD IN ('90','93','95')

'Direct Ship'
SELECT *
FROM da.DPR_DIRECT_SHIP dds
WHERE demand_loc = '5V'


'ISS IND'
SELECT SKU.STYLE_CD, SKU.COLOR_CD, SKU.ATTRIBUTE_CD, SKU.SIZE_CD, SKU.ISS_IND
FROM DA.SKU SKU
Where SKU.ISS_IND = 'Y' AND sku.STYLE_CD = 'BROCRA'
ORDER BY SKU.STYLE_CD, SKU.COLOR_CD, SKU.SIZE_CD

SELECT DPRCum.Style_CD, DPRCum.COLOR_CD, DPRCum.Cumulative_leadtime, DPRCum.RECEIPT_PERIOD 
FROM DA.DPR_CUMULATIVE_LEADTIME DPRCum;

WHERE STYLE_cd like '%TPC%'

SELECT PLAN_ORDER_DESCRIPTION.ORDER_VERSION, PLAN_ORDER_DESCRIPTION.ORDER_LABEL, PLAN_ORDER_DESCRIPTION.ORDER_ID, PLAN_ORDER_DESCRIPTION.PATH_ID, PLAN_ORDER_DESCRIPTION.BOM_ID, PLAN_ORDER_DESCRIPTION.ROUTE_ID, PLAN_ORDER_DESCRIPTION.PRIME_LOCATION, PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME, PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME, PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE, PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS, PLAN_ORDER_DESCRIPTION.UPDATE_CODE, PLAN_ORDER_DESCRIPTION.ORDER_STATUS, PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS, PLAN_ORDER_DESCRIPTION.OFFLOAD, PLAN_ORDER_DESCRIPTION.PROD_ORDER, PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND, PLAN_ORDER_DESCRIPTION.ENFORCEMENT, PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE, PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE, PLAN_ORDER_DESCRIPTION.PARENT_ORDER, PLAN_ORDER_DESCRIPTION.SUPER_ORDER, PLAN_ORDER_DESCRIPTION.PLANNER_CODE, PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY, PLAN_ORDER_DESCRIPTION.PARENT_COUPLING, PLAN_ORDER_DESCRIPTION.SKU, PLAN_ORDER_DESCRIPTION.LOCATION, PLAN_ORDER_DESCRIPTION.FAMILY, PLAN_ORDER_DESCRIPTION.STYLE, PLAN_ORDER_DESCRIPTION.COLOR, PLAN_ORDER_DESCRIPTION.ATTRIBUTE, PLAN_ORDER_DESCRIPTION.ORDER_SIZE, PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY, PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY, PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY, PLAN_ORDER_DESCRIPTION.DEMAND_TYPE, PLAN_ORDER_DESCRIPTION.WINDOW_START, PLAN_ORDER_DESCRIPTION.WINDOW_END, PLAN_ORDER_DESCRIPTION.SCHEDULED_START, PLAN_ORDER_DESCRIPTION.SCHEDULED_END, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END, PLAN_ORDER_DESCRIPTION.PRIORITY, PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR, PLAN_ORDER_DESCRIPTION.NOTE, PLAN_ORDER_DESCRIPTION.VENDOR_NO, PLAN_ORDER_DESCRIPTION.SCRAP_QTY, PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY, PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY, PLAN_ORDER_DESCRIPTION.ATP_DATE_IND, PLAN_ORDER_DESCRIPTION.BACKFILL_IND, PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD, PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO, PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD, PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD, PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD, PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD, PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO, PLAN_ORDER_DESCRIPTION.SELLING_SKU, PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD, PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN, PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO, PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC, PLAN_ORDER_DESCRIPTION.LW_COMPANY, PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
SCHEDULED_START / 1440 + 33231 AS "SewWeek",
SCHEDULED_END / 1440 + 33231 AS "DCWeek", ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC
FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW, AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD and plan_order_description.prime_location = '90'

SELECT *
FROM da.PLANNER 

SELECT *
FROM da.size_line

SELECT DPRCum.Style_CD, DPRCum.COLOR_CD, DPRCum.Cumulative_leadtime, DPRCum.RECEIPT_PERIOD
FROM DA.DPR_CUMULATIVE_LEADTIME DPRCum
WHERE (DPRCum.STYLE_CD = 'GOGTH2' AND DPRCum.COLOR_CD = 'ASF')
   OR (DPRCum.STYLE_CD = 'GPPMHP' AND DPRCum.COLOR_CD = 'ASF')
   OR (DPRCum.STYLE_CD = 'GUPSYB' AND DPRCum.COLOR_CD = 'ASF')
   OR (DPRCum.STYLE_CD = 'TGPTB6' AND DPRCum.COLOR_CD = 'ASF')
   OR (DPRCum.STYLE_CD = 'GUOCB8' AND DPRCum.COLOR_CD = 'N31')
   OR (DPRCum.STYLE_CD = 'GCPHP4' AND DPRCum.COLOR_CD = 'ASF')
   OR (DPRCum.STYLE_CD = 'GCEMW5' AND DPRCum.COLOR_CD = '00F')
   OR (DPRCum.STYLE_CD = 'GUOCH8' AND DPRCum.COLOR_CD = 'N31')
   OR (DPRCum.STYLE_CD = 'GOSSBK' AND DPRCum.COLOR_CD = 'ASF')
   OR (DPRCum.STYLE_CD = 'GOSSHP' AND DPRCum.COLOR_CD = 'ASF')


--- 'Check path ranking where is some plain code in it and pull all record'
   
SELECT *
FROM DA.PATH_RANKING pr
WHERE MFG_STYLE_CD IN (
    SELECT DISTINCT MFG_STYLE_CD
    FROM DA.PATH_RANKING
    WHERE MFG_PATH_ID = '93'
)

SELECT *
FROM DA.PATH_RANKING pr
WHERE STYLE = 'DAA633'
