SELECT * FROM da.dpr_sku_overrides
WHERE STYLE_CD in ('DF3488','DF3385','DFMLH3') AND color_CD = 'A6YM'

SELECT * FROM da.dpr_sku_overrides
WHERE STYLE_CD = 'DF3488'

SELECT * FROM da.DPR_SKU_OVERRIDES
WHERE (STYLE_CD = 'GOGTH2' AND COLOR_CD = 'ASF')
   OR (STYLE_CD = 'GPPMHP' AND COLOR_CD = 'ASF')
   OR (STYLE_CD = 'GUPSYB' AND COLOR_CD = 'ASF')
   OR (STYLE_CD = 'TGPTB6' AND COLOR_CD = 'ASF')
   OR (STYLE_CD = 'GUOCB8' AND COLOR_CD = 'N31')
   OR (STYLE_CD = 'GCPHP4' AND COLOR_CD = 'ASF')
   OR (STYLE_CD = 'GCEMW5' AND COLOR_CD = '00F')
   OR (STYLE_CD = 'GUOCH8' AND COLOR_CD = 'N31')
   OR (STYLE_CD = 'GOSSBK' AND COLOR_CD = 'ASF')
   OR (STYLE_CD = 'GOSSHP' AND COLOR_CD = 'ASF')
   
   SELECT owner, table_name 
   FROM all_tables 
   WHERE table_name = 'DPR_SKU_OVERRIDES';
   
  GRANT SELECT ON da.DPR_SKU_OVERRIDES TO tibunjon;