SELECT *
FROM da.HBI_SEQUENCED_DEMAND hsd 
WHERE hsd.BUSINESS_GROUP_LVL_1 = 'MEN'S UW'



SELECT *
FROM da.HBI_SEQUENCED_DEMAND hsd 
WHERE hsd.STYLE_CODE in ('2349C4','7460P4','MKCBX5') and hsd.size_code = '46';

SELECT *
FROM da.HBI_SEQUENCED_DEMAND hsd 
WHERE hsd.STYLE_CODE = '00489' and hsd.color_code = '9OD' and hsd.size_code = '41' and hsd.demand_type = 'STOCKTARGET'

SELECT Distinct hsd.product_code
FROM da.HBI_SEQUENCED_DEMAND hsd
--- where hsd.DC_LOCATION_CODE = '1090'
WHERE hsd.style_code in ('GPCMB1','GPCMH1') and hsd

and color size_code in ('OB','NB') 

SELECT DISTINCT hsd.STYLE_CODE
FROM da.HBI_SEQUENCED_DEMAND hsd
WHERE hsd.DC_LOCATION_CODE = '1090';

SELECT *
FROM IBP_PRODUCT IBPDownloads


SELECT DISTINCT stocking_category
FROM IBP_PRODUCT IBP
WHERE Product_group = 'Socks'

SELECT *
FROM IBP_PRODUCT IBP
where in'

SELECT *
FROM iss_Prod_order_activity
WHERE super_order = 'I002064310'

SELECT *
FROM da.ISS_PROD_SUMMARY ips 
--- WHERE super_order = 'I002064310'
WHERE SELLING_STYLE_CD = 'SCCRW6' AND SELLING_SIZE_CD = '42' --- AND selling_color_Cd in ('1GW','100')


SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'IBP_PRODUCT'

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'HBI_SEQUENCED_DEMAND'

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'ISS_PROD_SUMMARY'

SELECT *
FROM Da.HBI_DEMAND hd
WHERE STYLE_CODE in ('2349C4','7460P4','MKCBX5') and size_code in ('45','46')


--- New write Query

SELECT DISTINCT hsd.STYLE_CODE , hsd.COLOR_CODE 
FROM da.HBI_SEQUENCED_DEMAND hsd 
--- WHERE hsd.BUSINESS_GROUP_LVL_1 = 'MEN'S UW'

--- Check style IBP demand pass

SELECT aps_style_code, demand_type, demand_sub_type,
count (*), sum(current_qty)
FROM hbi_sequenced_demand
WHERE aps_style_code IN ('BYB115', 'BYB170', 'BYB540', 'CLS853')
GROUP BY aps_style_code, demand_type, demand_sub_type
ORDER BY aps_style_code, demand_type, demand_sub_type;


--- AVYX Demand Driver

select STYLE,COLOR,SIZE_CD,DEMAND_WEEKEND_DATE,round(sum(current_qty/12),0) Dozens from AVYX.AVYX_DEMAND_DRIVER where SELLING_STYLE_CD = '00489' group by DEMAND_WEEKEND_DATE,STYLE,COLOR,SIZE_CD
order by STYLE,COLOR,SIZE_CD,DEMAND_WEEKEND_DATE

--- MPS Order Detail

SELECT *
FROM DA.MPS_ORDER_DETAIL mod2
WHERE mod2.DEP_STYLE = 'PR4171' AND mod2.DEP_ATTRIBUTE_CD = 'DYEAUI'

--- TEMP

WITH style_attr AS (
    SELECT 'JE1078' AS style, 'DYEIUW' AS attribute_cd FROM dual UNION ALL
    SELECT 'JE1078','DYEOT5' FROM dual UNION ALL
    SELECT 'JE1078','DYEOUM' FROM dual UNION ALL
    SELECT 'JE1078','DYEYGG' FROM dual UNION ALL
    SELECT 'JE1078','DYEZ4U' FROM dual UNION ALL
    SELECT 'JE1078','DYEZRS' FROM dual UNION ALL

    SELECT 'JE107N','DYEODB' FROM dual UNION ALL
    SELECT 'JE107N','DYEOM5' FROM dual UNION ALL

    SELECT 'JE1B78','DYEIKZ' FROM dual UNION ALL
    SELECT 'JE1B78','DYEOT5' FROM dual UNION ALL
    SELECT 'JE1B78','DYEX2L' FROM dual UNION ALL
    SELECT 'JE1B78','DYEX2T' FROM dual UNION ALL
    SELECT 'JE1B78','DYEXE2' FROM dual UNION ALL
    SELECT 'JE1B78','DYEXIV' FROM dual UNION ALL

    SELECT 'JE1B7N','DYEKXG' FROM dual UNION ALL
    SELECT 'JE1B7N','DYEOM5' FROM dual UNION ALL

    SELECT 'JE1B7S','DYEHYC' FROM dual UNION ALL
    SELECT 'JE1B7S','DYEHYY' FROM dual UNION ALL

    SELECT 'JE2271','DYEKMA' FROM dual UNION ALL
    SELECT 'JE2271','DYEOAC' FROM dual UNION ALL
    SELECT 'JE2271','DYEOKO' FROM dual UNION ALL

    SELECT 'JE2859','DYEQ1A' FROM dual UNION ALL
    SELECT 'JE2859','DYEQH3' FROM dual UNION ALL
    SELECT 'JE2859','DYEU5K' FROM dual UNION ALL
    SELECT 'JE2859','DYEY9S' FROM dual UNION ALL
    SELECT 'JE2859','DYEYCL' FROM dual UNION ALL
    SELECT 'JE2859','DYEZCH' FROM dual UNION ALL
    SELECT 'JE2859','DYEZKC' FROM dual UNION ALL
    SELECT 'JE2859','DYEZLN' FROM dual UNION ALL
    SELECT 'JE2859','DYEZQG' FROM dual UNION ALL
    SELECT 'JE2859','DYEZRG' FROM dual UNION ALL

    SELECT 'JE2W71','DYEYOM' FROM dual UNION ALL
    SELECT 'JE2X59','DYEZCA' FROM dual UNION ALL

    SELECT 'JE4171','DYEIIC' FROM dual UNION ALL
    SELECT 'JE4171','DYELTM' FROM dual UNION ALL
    SELECT 'JE4171','DYEWAW' FROM dual UNION ALL
    SELECT 'JE4171','DYEXA1' FROM dual UNION ALL
    SELECT 'JE4171','DYEXDD' FROM dual UNION ALL
    SELECT 'JE4171','DYEXWX' FROM dual UNION ALL
    SELECT 'JE4171','DYEYAC' FROM dual UNION ALL
    SELECT 'JE4171','DYEYCL' FROM dual UNION ALL
    SELECT 'JE4171','DYEYKS' FROM dual UNION ALL
    SELECT 'JE4171','DYEZ00' FROM dual UNION ALL
    SELECT 'JE4171','DYEZOG' FROM dual UNION ALL
    SELECT 'JE4171','DYEZP4' FROM dual UNION ALL
    SELECT 'JE4171','DYEZQG' FROM dual UNION ALL
    SELECT 'JE4171','DYEZVX' FROM dual UNION ALL

    SELECT 'JE4209','DYEJUC' FROM dual UNION ALL
    SELECT 'JE4209','DYEO8B' FROM dual UNION ALL
    SELECT 'JE4209','DYEYZI' FROM dual UNION ALL
    SELECT 'JE4209','DYEZLV' FROM dual UNION ALL

    SELECT 'JE4B07','DYEYOM' FROM dual UNION ALL

    SELECT 'JE4W71','DYE2P0' FROM dual UNION ALL
    SELECT 'JE4W71','DYE2Q0' FROM dual UNION ALL
    SELECT 'JE4W71','DYEJ9G' FROM dual UNION ALL
    SELECT 'JE4W71','DYEQBL' FROM dual UNION ALL
    SELECT 'JE4W71','DYEQGV' FROM dual UNION ALL
    SELECT 'JE4W71','DYEQNS' FROM dual UNION ALL
    SELECT 'JE4W71','DYEUII' FROM dual UNION ALL
    SELECT 'JE4W71','DYEUJP' FROM dual UNION ALL
    SELECT 'JE4W71','DYEUXH' FROM dual UNION ALL
    SELECT 'JE4W71','DYEVO1' FROM dual UNION ALL
    SELECT 'JE4W71','DYEWHX' FROM dual UNION ALL
    SELECT 'JE4W71','DYEZCA' FROM dual UNION ALL

    SELECT 'JE5348','DYEH4A' FROM dual UNION ALL
    SELECT 'JE5348','DYELHI' FROM dual UNION ALL
    SELECT 'JE5348','DYEQ7Q' FROM dual UNION ALL
    SELECT 'JE5348','DYEQ8S' FROM dual UNION ALL
    SELECT 'JE5348','DYEQI2' FROM dual UNION ALL
    SELECT 'JE5348','DYEQSV' FROM dual UNION ALL
    SELECT 'JE5348','DYEUVU' FROM dual UNION ALL
    SELECT 'JE5348','DYEUYO' FROM dual UNION ALL
    SELECT 'JE5348','DYEXA1' FROM dual UNION ALL
    SELECT 'JE5348','DYEXIV' FROM dual UNION ALL
    SELECT 'JE5348','DYEXQ5' FROM dual UNION ALL
    SELECT 'JE5348','DYEXTC' FROM dual UNION ALL
    SELECT 'JE5348','DYEY3P' FROM dual UNION ALL
    SELECT 'JE5348','DYEYAB' FROM dual UNION ALL
    SELECT 'JE5348','DYEYLX' FROM dual UNION ALL
    SELECT 'JE5348','DYEYW7' FROM dual UNION ALL
    SELECT 'JE5348','DYEYXH' FROM dual UNION ALL
    SELECT 'JE5348','DYEZ0Y' FROM dual UNION ALL
    SELECT 'JE5348','DYEZ1U' FROM dual UNION ALL
    SELECT 'JE5348','DYEZC3' FROM dual UNION ALL
    SELECT 'JE5348','DYEZCA' FROM dual UNION ALL
    SELECT 'JE5348','DYEZCB' FROM dual UNION ALL
    SELECT 'JE5348','DYEZCC' FROM dual UNION ALL
    SELECT 'JE5348','DYEZDQ' FROM dual UNION ALL
    SELECT 'JE5348','DYEZL5' FROM dual UNION ALL
    SELECT 'JE5348','DYEZP4' FROM dual UNION ALL
    SELECT 'JE5348','DYEZQG' FROM dual UNION ALL
    SELECT 'JE5348','DYEZRO' FROM dual UNION ALL

    SELECT 'JE5391','DYEQ2E' FROM dual UNION ALL
    SELECT 'JE5391','DYEXWX' FROM dual UNION ALL

    SELECT 'JE5463','DYEIKZ' FROM dual UNION ALL
    SELECT 'JE5463','DYEOUM' FROM dual
)
SELECT md.*
FROM da.MPS_DETAIL md
JOIN style_attr sa
  ON md.style = sa.style
 AND md.attribute_cd = sa.attribute_cd;

SELECT *
FROM da.HBI_SEQUENCED_DEMAND hsd
WHERE STYLE_CODE IN ('GOGTH2','GPPMHP','GUPSYB')

SELECT *
FROM da.HBI_SEQUENCED_DEMAND hsd
WHERE STYLE_CODE = 'NCCNP3'

--- check HBI sequence demand updated date

SELECT
    STYLE_CODE,
    COLOR_CODE,
    CUMULATIVE_LEADTIME,
    CREATE_DATE
FROM (
    SELECT
        STYLE_CODE,
        COLOR_CODE,
        CUMULATIVE_LEADTIME,
        CREATE_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY STYLE_CODE, COLOR_CODE 
            ORDER BY CREATE_DATE DESC
        ) AS rn
    FROM da.HBI_SEQUENCED_DEMAND
    WHERE (STYLE_CODE, COLOR_CODE) IN (
        ('GOGTH2', 'ASF'),
        ('GPPMHP', 'ASF'),
        ('GUPSYB', 'ASF'),
        ('TGPTB6', 'ASF'),
        ('GUOCB8', 'N31'),
        ('GCPHP4', 'ASF'),
        ('GCEMW5', '00F'),
        ('GUOCH8', 'N31'),
        ('GOSSBK', 'ASF'),
        ('GOSSHP', 'ASF')
    )
) ranked
WHERE rn = 1


--- DPR LEadtime Source

SELECT *
FROM DA.IBP_CUMULATIVE_LEADTIME
WHERE style_CD in ('DF3488','DF3385','DFMLH3') AND color_CD = 'A6YM'


SELECT DISTINCT STYLE_CD, COLOR_CD, CUMULATIVE_LEAD_TIME, LEAD_TIME_SOURCE 
FROM DA.IBP_CUMULATIVE_LEADTIME
WHERE
    (STYLE_CD = 'L5BBP3' AND COLOR_CD = 'RP02') OR
    (STYLE_CD = 'L5BBP3' AND COLOR_CD = 'RP03') OR
    (STYLE_CD = 'L5LBP3' AND COLOR_CD = 'RP01') OR
    (STYLE_CD = 'L5LBP3' AND COLOR_CD = 'RP02') OR
    (STYLE_CD = 'RY25RT' AND COLOR_CD = 'NYD')

SELECT DISTINCT STYLE_CD, COLOR_CD, CUMULATIVE_LEAD_TIME, LEAD_TIME_SOURCE
FROM DA.IBP_CUMULATIVE_LEADTIME
WHERE
    (STYLE_CD = 'CUSBP4' AND COLOR_CD = 'A639') OR
    (STYLE_CD = 'CUSBP4' AND COLOR_CD = 'A7L2') OR
    (STYLE_CD = 'CUSBP4' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'CUSKP4' AND COLOR_CD = 'A7L2') OR
    (STYLE_CD = 'CUSKP4' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'CUCCP4' AND COLOR_CD = 'WHD') OR
    (STYLE_CD = 'CUCTP4' AND COLOR_CD = 'WHD') OR
    (STYLE_CD = 'CUCVP4' AND COLOR_CD = 'WHD') OR
    (STYLE_CD = 'L117HX' AND COLOR_CD = 'AAM9') OR
    (STYLE_CD = 'L5BBP3' AND COLOR_CD = 'RP02') OR
    (STYLE_CD = 'L5BBP3' AND COLOR_CD = 'RP03') OR
    (STYLE_CD = 'L5LBP3' AND COLOR_CD = 'RP01') OR
    (STYLE_CD = 'L5LBP3' AND COLOR_CD = 'RP02') OR
    (STYLE_CD = 'LLPLP3' AND COLOR_CD = 'RP03') OR
    (STYLE_CD = 'MNCBH6' AND COLOR_CD = 'AB3K') OR
    (STYLE_CD = 'MNCKH6' AND COLOR_CD = 'AB3K') OR
    (STYLE_CD = 'NCTRP3' AND COLOR_CD = 'RHD') OR
    (STYLE_CD = 'NWBBP3' AND COLOR_CD = '4KM') OR
    (STYLE_CD = 'NWBBP3' AND COLOR_CD = 'Q7Q') OR
    (STYLE_CD = 'NWBBP3' AND COLOR_CD = 'QC9') OR
    (STYLE_CD = 'NWBBP3' AND COLOR_CD = 'S6Z') OR
    (STYLE_CD = 'NWLBP3' AND COLOR_CD = '4KM') OR
    (STYLE_CD = 'NWSBP3' AND COLOR_CD = 'S6Z') OR
    (STYLE_CD = 'NXWBP3' AND COLOR_CD = '3ZT') OR
    (STYLE_CD = 'NXWBP3' AND COLOR_CD = 'QLD') OR
    (STYLE_CD = 'L009ZQ' AND COLOR_CD = '00D') OR
    (STYLE_CD = 'MPBPF2' AND COLOR_CD = 'AAN7') OR
    (STYLE_CD = 'MPBPF2' AND COLOR_CD = 'AAP2') OR
    (STYLE_CD = 'P171RL' AND COLOR_CD = '2FO') OR
    (STYLE_CD = 'PK04RT' AND COLOR_CD = 'JUD') OR
    (STYLE_CD = 'PK04RT' AND COLOR_CD = 'W7D') OR
    (STYLE_CD = 'PK04RX' AND COLOR_CD = 'W7D') OR
    (STYLE_CD = 'PK05RT' AND COLOR_CD = 'JUD') OR
    (STYLE_CD = 'PK05RT' AND COLOR_CD = 'LGD') OR
    (STYLE_CD = 'PK05RT' AND COLOR_CD = 'W7D') OR
    (STYLE_CD = 'PK05RX' AND COLOR_CD = 'W7D') OR
    (STYLE_CD = 'PK08RT' AND COLOR_CD = 'JUD') OR
    (STYLE_CD = 'PK08RT' AND COLOR_CD = 'LGD') OR
    (STYLE_CD = 'PK08RT' AND COLOR_CD = 'W7D') OR
    (STYLE_CD = 'PK08RX' AND COLOR_CD = 'JUD') OR
    (STYLE_CD = 'PK08RX' AND COLOR_CD = 'LGD') OR
    (STYLE_CD = 'PK08RX' AND COLOR_CD = 'W7D') OR
    (STYLE_CD = 'PK08SR' AND COLOR_CD = 'W7D') OR
    (STYLE_CD = 'PLCPPP' AND COLOR_CD = '0HD') OR
    (STYLE_CD = 'PLCPPP' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCPPP' AND COLOR_CD = 'W8D') OR
    (STYLE_CD = 'PLCPPT' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCPPX' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCTCR' AND COLOR_CD = '0HD') OR
    (STYLE_CD = 'PLCTCR' AND COLOR_CD = 'AACV') OR
    (STYLE_CD = 'PLCTCR' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCTCR' AND COLOR_CD = 'W8D') OR
    (STYLE_CD = 'PLCTCT' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCTCX' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCTHR' AND COLOR_CD = '0HD') OR
    (STYLE_CD = 'PLCTHR' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCTHR' AND COLOR_CD = 'W8D') OR
    (STYLE_CD = 'PLCTJR' AND COLOR_CD = '03D') OR
    (STYLE_CD = 'PLCTJR' AND COLOR_CD = '9VD') OR
    (STYLE_CD = 'PLCTJR' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'PLCTSR' AND COLOR_CD = '0HD') OR
    (STYLE_CD = 'PLCTSR' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCTSR' AND COLOR_CD = 'W8D') OR
    (STYLE_CD = 'PLCTST' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'PLCTSX' AND COLOR_CD = 'AADV') OR
    (STYLE_CD = 'POWLSR' AND COLOR_CD = 'AA7V') OR
    (STYLE_CD = 'POWLSR' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'POWLSR' AND COLOR_CD = 'W2D') OR
    (STYLE_CD = 'POWPJR' AND COLOR_CD = '03D') OR
    (STYLE_CD = 'POWPJR' AND COLOR_CD = 'AA7V') OR
    (STYLE_CD = 'POWPJR' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'POWPJR' AND COLOR_CD = 'W2D') OR
    (STYLE_CD = 'PWLE2F' AND COLOR_CD = 'AHRR') OR
    (STYLE_CD = 'PWLE2R' AND COLOR_CD = 'AHRR') OR
    (STYLE_CD = 'RY21RX' AND COLOR_CD = '9VD') OR
    (STYLE_CD = 'RY21RX' AND COLOR_CD = 'WHD') OR
    (STYLE_CD = 'RY25RT' AND COLOR_CD = 'NYD') OR
    (STYLE_CD = 'RY25RT' AND COLOR_CD = 'Q3D') OR
    (STYLE_CD = 'RY25RX' AND COLOR_CD = 'NYD') OR
    (STYLE_CD = 'RY25RX' AND COLOR_CD = 'Q3D') OR
    (STYLE_CD = 'RY27RX' AND COLOR_CD = 'C1D') OR
    (STYLE_CD = 'RY27RX' AND COLOR_CD = 'NYD') OR
    (STYLE_CD = 'RY27RX' AND COLOR_CD = 'Q3D') OR
    (STYLE_CD = 'RY28RT' AND COLOR_CD = 'C1D') OR
    (STYLE_CD = 'RY28RT' AND COLOR_CD = 'NYD') OR
    (STYLE_CD = 'RY28RT' AND COLOR_CD = 'Q3D') OR
    (STYLE_CD = 'L008ZQ' AND COLOR_CD = '00D') OR
    (STYLE_CD = 'LEMCP2' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'LEMCP2' AND COLOR_CD = 'WHD') OR
    (STYLE_CD = 'LEMVP2' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'LEMVP2' AND COLOR_CD = 'WHD') OR
    (STYLE_CD = 'LFC2P3' AND COLOR_CD = 'PBD') OR
    (STYLE_CD = 'NCCNP3' AND COLOR_CD = '9OD') OR
    (STYLE_CD = 'NCCNP3' AND COLOR_CD = 'G2M') OR
    (STYLE_CD = 'NCCNP3' AND COLOR_CD = 'U2O') OR
    (STYLE_CD = 'NCCNP3' AND COLOR_CD = 'U5O') OR
    (STYLE_CD = 'NCTKP3' AND COLOR_CD = '9OD') OR
    (STYLE_CD = 'NCVNP3' AND COLOR_CD = '9OD') OR
    (STYLE_CD = 'NCVNP3' AND COLOR_CD = 'G2M') OR
    (STYLE_CD = 'NCVNP3' AND COLOR_CD = 'U2O') OR
    (STYLE_CD = 'NCVNP3' AND COLOR_CD = 'U5O') OR
    (STYLE_CD = 'NSCNP3' AND COLOR_CD = '9OD') OR
    (STYLE_CD = 'NSCNP3' AND COLOR_CD = 'SPA1') OR
    (STYLE_CD = 'NSCNP3' AND COLOR_CD = 'SPA3') OR
    (STYLE_CD = 'NSCNP3' AND COLOR_CD = 'U2O') OR
    (STYLE_CD = 'NSCNP3' AND COLOR_CD = 'U5O') OR
    (STYLE_CD = 'NSTKP3' AND COLOR_CD = '9OD') OR
    (STYLE_CD = 'NSVNP3' AND COLOR_CD = '9OD') OR
    (STYLE_CD = 'NSVNP3' AND COLOR_CD = 'U5O') OR
    (STYLE_CD = 'NWC2P3' AND COLOR_CD = 'AROB') OR
    (STYLE_CD = 'NWC2P3' AND COLOR_CD = 'ARRB') OR
    (STYLE_CD = 'NWV2P3' AND COLOR_CD = 'AROB') OR
    (STYLE_CD = 'NWV2P3' AND COLOR_CD = 'ARRB') OR
    (STYLE_CD = 'BBL2WB' AND COLOR_CD = 'ASU') OR
    (STYLE_CD = 'BBL2WF' AND COLOR_CD = 'ASU') OR
    (STYLE_CD = 'BBL2WN' AND COLOR_CD = 'ASU') OR
    (STYLE_CD = 'GBLWM1' AND COLOR_CD = 'ASF') OR
    (STYLE_CD = 'GBLWM2' AND COLOR_CD = 'ASF') OR
    (STYLE_CD = 'GBLWM3' AND COLOR_CD = 'ASF')
    

SELECT DISTINCT 
    APS_STYLE_CODE, 
    APS_COLOR_CODE, 
    CUMULATIVE_LEADTIME
FROM da.HBI_SEQUENCED_DEMAND hsd
WHERE
    (STYLE_CODE = 'L5BBP3' AND COLOR_CODE = 'RP02') OR
    (STYLE_CODE = 'L5BBP3' AND COLOR_CODE = 'RP03') OR
    (STYLE_CODE = 'L5LBP3' AND COLOR_CODE = 'RP01') OR
    (STYLE_CODE = 'L5LBP3' AND COLOR_CODE = 'RP02') OR
    (STYLE_CODE = 'RY25RT' AND COLOR_CODE = 'NYD');
    

SELECT DISTINCT APS_STYLE_CODE, APS_COLOR_CODE, CUMULATIVE_LEADTIME
FROM da.HBI_SEQUENCED_DEMAND hsd
WHERE
    (STYLE_CODE = 'CUSBP4' AND COLOR_CODE = 'A639') OR
    (STYLE_CODE = 'CUSBP4' AND COLOR_CODE = 'A7L2') OR
    (STYLE_CODE = 'CUSBP4' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'CUSKP4' AND COLOR_CODE = 'A7L2') OR
    (STYLE_CODE = 'CUSKP4' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'CUCCP4' AND COLOR_CODE = 'WHD') OR
    (STYLE_CODE = 'CUCTP4' AND COLOR_CODE = 'WHD') OR
    (STYLE_CODE = 'CUCVP4' AND COLOR_CODE = 'WHD') OR
    (STYLE_CODE = 'L117HX' AND COLOR_CODE = 'AAM9') OR
    (STYLE_CODE = 'L5BBP3' AND COLOR_CODE = 'RP02') OR
    (STYLE_CODE = 'L5BBP3' AND COLOR_CODE = 'RP03') OR
    (STYLE_CODE = 'L5LBP3' AND COLOR_CODE = 'RP01') OR
    (STYLE_CODE = 'L5LBP3' AND COLOR_CODE = 'RP02') OR
    (STYLE_CODE = 'LLPLP3' AND COLOR_CODE = 'RP03') OR
    (STYLE_CODE = 'MNCBH6' AND COLOR_CODE = 'AB3K') OR
    (STYLE_CODE = 'MNCKH6' AND COLOR_CODE = 'AB3K') OR
    (STYLE_CODE = 'NCTRP3' AND COLOR_CODE = 'RHD') OR
    (STYLE_CODE = 'NWBBP3' AND COLOR_CODE = '4KM') OR
    (STYLE_CODE = 'NWBBP3' AND COLOR_CODE = 'Q7Q') OR
    (STYLE_CODE = 'NWBBP3' AND COLOR_CODE = 'QC9') OR
    (STYLE_CODE = 'NWBBP3' AND COLOR_CODE = 'S6Z') OR
    (STYLE_CODE = 'NWLBP3' AND COLOR_CODE = '4KM') OR
    (STYLE_CODE = 'NWSBP3' AND COLOR_CODE = 'S6Z') OR
    (STYLE_CODE = 'NXWBP3' AND COLOR_CODE = '3ZT') OR
    (STYLE_CODE = 'NXWBP3' AND COLOR_CODE = 'QLD') OR
    (STYLE_CODE = 'L009ZQ' AND COLOR_CODE = '00D') OR
    (STYLE_CODE = 'MPBPF2' AND COLOR_CODE = 'AAN7') OR
    (STYLE_CODE = 'MPBPF2' AND COLOR_CODE = 'AAP2') OR
    (STYLE_CODE = 'P171RL' AND COLOR_CODE = '2FO') OR
    (STYLE_CODE = 'PK04RT' AND COLOR_CODE = 'JUD') OR
    (STYLE_CODE = 'PK04RT' AND COLOR_CODE = 'W7D') OR
    (STYLE_CODE = 'PK04RX' AND COLOR_CODE = 'W7D') OR
    (STYLE_CODE = 'PK05RT' AND COLOR_CODE = 'JUD') OR
    (STYLE_CODE = 'PK05RT' AND COLOR_CODE = 'LGD') OR
    (STYLE_CODE = 'PK05RT' AND COLOR_CODE = 'W7D') OR
    (STYLE_CODE = 'PK05RX' AND COLOR_CODE = 'W7D') OR
    (STYLE_CODE = 'PK08RT' AND COLOR_CODE = 'JUD') OR
    (STYLE_CODE = 'PK08RT' AND COLOR_CODE = 'LGD') OR
    (STYLE_CODE = 'PK08RT' AND COLOR_CODE = 'W7D') OR
    (STYLE_CODE = 'PK08RX' AND COLOR_CODE = 'JUD') OR
    (STYLE_CODE = 'PK08RX' AND COLOR_CODE = 'LGD') OR
    (STYLE_CODE = 'PK08RX' AND COLOR_CODE = 'W7D') OR
    (STYLE_CODE = 'PK08SR' AND COLOR_CODE = 'W7D') OR
    (STYLE_CODE = 'PLCPPP' AND COLOR_CODE = '0HD') OR
    (STYLE_CODE = 'PLCPPP' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCPPP' AND COLOR_CODE = 'W8D') OR
    (STYLE_CODE = 'PLCPPT' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCPPX' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCTCR' AND COLOR_CODE = '0HD') OR
    (STYLE_CODE = 'PLCTCR' AND COLOR_CODE = 'AACV') OR
    (STYLE_CODE = 'PLCTCR' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCTCR' AND COLOR_CODE = 'W8D') OR
    (STYLE_CODE = 'PLCTCT' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCTCX' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCTHR' AND COLOR_CODE = '0HD') OR
    (STYLE_CODE = 'PLCTHR' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCTHR' AND COLOR_CODE = 'W8D') OR
    (STYLE_CODE = 'PLCTJR' AND COLOR_CODE = '03D') OR
    (STYLE_CODE = 'PLCTJR' AND COLOR_CODE = '9VD') OR
    (STYLE_CODE = 'PLCTJR' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'PLCTSR' AND COLOR_CODE = '0HD') OR
    (STYLE_CODE = 'PLCTSR' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCTSR' AND COLOR_CODE = 'W8D') OR
    (STYLE_CODE = 'PLCTST' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'PLCTSX' AND COLOR_CODE = 'AADV') OR
    (STYLE_CODE = 'POWLSR' AND COLOR_CODE = 'AA7V') OR
    (STYLE_CODE = 'POWLSR' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'POWLSR' AND COLOR_CODE = 'W2D') OR
    (STYLE_CODE = 'POWPJR' AND COLOR_CODE = '03D') OR
    (STYLE_CODE = 'POWPJR' AND COLOR_CODE = 'AA7V') OR
    (STYLE_CODE = 'POWPJR' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'POWPJR' AND COLOR_CODE = 'W2D') OR
    (STYLE_CODE = 'PWLE2F' AND COLOR_CODE = 'AHRR') OR
    (STYLE_CODE = 'PWLE2R' AND COLOR_CODE = 'AHRR') OR
    (STYLE_CODE = 'RY21RX' AND COLOR_CODE = '9VD') OR
    (STYLE_CODE = 'RY21RX' AND COLOR_CODE = 'WHD') OR
    (STYLE_CODE = 'RY25RT' AND COLOR_CODE = 'NYD') OR
    (STYLE_CODE = 'RY25RT' AND COLOR_CODE = 'Q3D') OR
    (STYLE_CODE = 'RY25RX' AND COLOR_CODE = 'NYD') OR
    (STYLE_CODE = 'RY25RX' AND COLOR_CODE = 'Q3D') OR
    (STYLE_CODE = 'RY27RX' AND COLOR_CODE = 'C1D') OR
    (STYLE_CODE = 'RY27RX' AND COLOR_CODE = 'NYD') OR
    (STYLE_CODE = 'RY27RX' AND COLOR_CODE = 'Q3D') OR
    (STYLE_CODE = 'RY28RT' AND COLOR_CODE = 'C1D') OR
    (STYLE_CODE = 'RY28RT' AND COLOR_CODE = 'NYD') OR
    (STYLE_CODE = 'RY28RT' AND COLOR_CODE = 'Q3D') OR
    (STYLE_CODE = 'L008ZQ' AND COLOR_CODE = '00D') OR
    (STYLE_CODE = 'LEMCP2' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'LEMCP2' AND COLOR_CODE = 'WHD') OR
    (STYLE_CODE = 'LEMVP2' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'LEMVP2' AND COLOR_CODE = 'WHD') OR
    (STYLE_CODE = 'LFC2P3' AND COLOR_CODE = 'PBD') OR
    (STYLE_CODE = 'NCCNP3' AND COLOR_CODE = '9OD') OR
    (STYLE_CODE = 'NCCNP3' AND COLOR_CODE = 'G2M') OR
    (STYLE_CODE = 'NCCNP3' AND COLOR_CODE = 'U2O') OR
    (STYLE_CODE = 'NCCNP3' AND COLOR_CODE = 'U5O') OR
    (STYLE_CODE = 'NCTKP3' AND COLOR_CODE = '9OD') OR
    (STYLE_CODE = 'NCVNP3' AND COLOR_CODE = '9OD') OR
    (STYLE_CODE = 'NCVNP3' AND COLOR_CODE = 'G2M') OR
    (STYLE_CODE = 'NCVNP3' AND COLOR_CODE = 'U2O') OR
    (STYLE_CODE = 'NCVNP3' AND COLOR_CODE = 'U5O') OR
    (STYLE_CODE = 'NSCNP3' AND COLOR_CODE = '9OD') OR
    (STYLE_CODE = 'NSCNP3' AND COLOR_CODE = 'SPA1') OR
    (STYLE_CODE = 'NSCNP3' AND COLOR_CODE = 'SPA3') OR
    (STYLE_CODE = 'NSCNP3' AND COLOR_CODE = 'U2O') OR
    (STYLE_CODE = 'NSCNP3' AND COLOR_CODE = 'U5O') OR
    (STYLE_CODE = 'NSTKP3' AND COLOR_CODE = '9OD') OR
    (STYLE_CODE = 'NSVNP3' AND COLOR_CODE = '9OD') OR
    (STYLE_CODE = 'NSVNP3' AND COLOR_CODE = 'U5O') OR
    (STYLE_CODE = 'NWC2P3' AND COLOR_CODE = 'AROB') OR
    (STYLE_CODE = 'NWC2P3' AND COLOR_CODE = 'ARRB') OR
    (STYLE_CODE = 'NWV2P3' AND COLOR_CODE = 'AROB') OR
    (STYLE_CODE = 'NWV2P3' AND COLOR_CODE = 'ARRB') OR
    (STYLE_CODE = 'BBL2WB' AND COLOR_CODE = 'ASU') OR
    (STYLE_CODE = 'BBL2WF' AND COLOR_CODE = 'ASU') OR
    (STYLE_CODE = 'BBL2WN' AND COLOR_CODE = 'ASU') OR
    (STYLE_CODE = 'GBLWM1' AND COLOR_CODE = 'ASF') OR
    (STYLE_CODE = 'GBLWM2' AND COLOR_CODE = 'ASF') OR
    (STYLE_CODE = 'GBLWM3' AND COLOR_CODE = 'ASF')    
