SELECT DISTINCT IBP.FCST_SKU_KEY
FROM DA.IBP_TOTAL_DEMAND_OUTPUT_CPS IBP
WHERE IBP.STYLECODE = '2252P6'

SELECT DISTINCT IBP.FISCALYEAR
FROM DA.IBP_TOTAL_DEMAND_OUTPUT_CPS IBP
WHERE IBP.STYLECODE = '2252P6'

SELECT *
FROM DA.IBP_TOTAL_DEMAND_OUTPUT_CPS IBP
WHERE IBP.STYLECODE = '2252P6'

SELECT DISTINCT IBP.FISCALYEAR
FROM DA.IBP_TOTAL_DEMAND_OUTPUT_CPS IBP
WHERE IBP.STYLECODE = '2252P6'

SELECT DISTINCT IBP.FISCALYEAR, IBP.FISCALPERIOD, IBP.FISCALWEEK, IBP.IN_DC_DATE 
FROM DA.IBP_TOTAL_DEMAND_OUTPUT_CPS IBP
WHERE IBP.STYLECODE in ('2252P6','2349Z5','7460P6')

SELECT *
FROM da.IBP_PRODUCT ip
WHERE CAST (ip.DISCONTINUE_DATE AS datetime) < '2025-08-01 00:00:00:000'

SELECT *
FROM da.IBP_PRODUCT ip
WHERE CAST (ip.DISCONTINUE_DATE AS datetime) < '2025-08-01 00:00:00:000'

SELECT *
FROM da.IBP_PRODUCT ip
WHERE ip.DISCONTINUE_DATE < '2025-08-01 00:00:00.000';

SELECT *
FROM da.IBP_PRODUCT ip
WHERE ip.DISCONTINUE_DATE < TO_TIMESTAMP('2026-12-31 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3') AND ip.DISCONTINUE_DATE > TO_TIMESTAMP('2025-01-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')


SELECT DISTINCT IP.style_code
FROM da.IBP_PRODUCT ip
WHERE ip.style_code like 'J8%'

SELECT *
FROM da.IBP_PRODUCT ip
WHERE ip.style_code like '%7764M6%'

SELECT STYLE_CODE, AVG(STANDARD_COST) AS STDCOST
FROM da.IBP_PRODUCT
WHERE style_code LIKE '%2252%'
GROUP BY STYLE_CODE;

SELECT CONFLICT_PATH,CONFLICT_SKU,CONFLICT_REASON,QUANTITY,PLANNER_CODE,LOCATION,FAMILY,STYLE,COLOR,ATTRIBUTE,ORDER_SIZE,DEMAND_TYPE,ORDER_SOURCE_CD
FROM plan_order_conflict c 
inner join plan_order_description a 
on a.order_version = c.order_version 
and a.order_label = c.order_label
WHERE STYLE IN(SELECT  DISTINCT AVYX_DEMAND_DRIVER.SELLING_STYLE_CD
FROM AVYX_DEMAND_DRIVER
LEFT JOIN (SELECT DISTINCT MV_SKU.STYLE_CD, MV_SKU.COLOR_CD, MV_SKU.ATTRIBUTE_CD, MV_SKU.SIZE_CD,MV_SKU.ISS_IND,current_date FROM DA.MV_SKU MV_SKU) B on  AVYX_DEMAND_DRIVER.SELLING_STYLE_CD = B.STYLE_CD AND AVYX_DEMAND_DRIVER.SELLING_COLOR_CD = B.COLOR_CD AND AVYX_DEMAND_DRIVER.SIZE_CD = B.SIZE_CD
WHERE  B.ISS_IND = 'Y' and AVYX_DEMAND_DRIVER.RULE_NUMBER <=2500)
ORDER BY CONFLICT_SKU ASC


SELECT *
FROM da.IBP_PRODUCT ip
WHERE ip.style_code in ('GPCMB1','GPCMH1')