SELECT PLAN_ORDER_DESCRIPTION.ORDER_VERSION, PLAN_ORDER_DESCRIPTION.ORDER_LABEL, PLAN_ORDER_DESCRIPTION.ORDER_ID, PLAN_ORDER_DESCRIPTION.PATH_ID, PLAN_ORDER_DESCRIPTION.BOM_ID, PLAN_ORDER_DESCRIPTION.ROUTE_ID, PLAN_ORDER_DESCRIPTION.PRIME_LOCATION, PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME, PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME, PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE, PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS, PLAN_ORDER_DESCRIPTION.UPDATE_CODE, PLAN_ORDER_DESCRIPTION.ORDER_STATUS, PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS, PLAN_ORDER_DESCRIPTION.OFFLOAD, PLAN_ORDER_DESCRIPTION.PROD_ORDER, PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND, PLAN_ORDER_DESCRIPTION.ENFORCEMENT, PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE, PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE, PLAN_ORDER_DESCRIPTION.PARENT_ORDER, PLAN_ORDER_DESCRIPTION.SUPER_ORDER, PLAN_ORDER_DESCRIPTION.PLANNER_CODE, PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY, PLAN_ORDER_DESCRIPTION.PARENT_COUPLING, PLAN_ORDER_DESCRIPTION.SKU, PLAN_ORDER_DESCRIPTION.LOCATION, PLAN_ORDER_DESCRIPTION.FAMILY, PLAN_ORDER_DESCRIPTION.STYLE, PLAN_ORDER_DESCRIPTION.COLOR, PLAN_ORDER_DESCRIPTION.ATTRIBUTE, PLAN_ORDER_DESCRIPTION.ORDER_SIZE, PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY, PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY, PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY, PLAN_ORDER_DESCRIPTION.DEMAND_TYPE, PLAN_ORDER_DESCRIPTION.WINDOW_START, PLAN_ORDER_DESCRIPTION.WINDOW_END, PLAN_ORDER_DESCRIPTION.SCHEDULED_START, PLAN_ORDER_DESCRIPTION.SCHEDULED_END, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END, PLAN_ORDER_DESCRIPTION.PRIORITY, PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR, PLAN_ORDER_DESCRIPTION.NOTE, PLAN_ORDER_DESCRIPTION.VENDOR_NO, PLAN_ORDER_DESCRIPTION.SCRAP_QTY, PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY, PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY, PLAN_ORDER_DESCRIPTION.ATP_DATE_IND, PLAN_ORDER_DESCRIPTION.BACKFILL_IND, PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD, PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO, PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD, PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD, PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD, PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD, PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO, PLAN_ORDER_DESCRIPTION.SELLING_SKU, PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD, PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN, PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO, PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC, PLAN_ORDER_DESCRIPTION.LW_COMPANY, PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
SCHEDULED_START / 1440 + 33231 AS "SewWeek",
SCHEDULED_END / 1440 + 33231 AS "DCWeek", ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC
FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW, AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD AND ISS_CAP_ALLOC_XREF_VIEW.sew_Alloc = 'WM_G20' and plan_order_description.prime_location IN ('93','95','C9') 

SELECT PLAN_ORDER_DESCRIPTION.ORDER_VERSION, PLAN_ORDER_DESCRIPTION.ORDER_LABEL, PLAN_ORDER_DESCRIPTION.ORDER_ID, PLAN_ORDER_DESCRIPTION.PATH_ID, PLAN_ORDER_DESCRIPTION.BOM_ID, PLAN_ORDER_DESCRIPTION.ROUTE_ID, PLAN_ORDER_DESCRIPTION.PRIME_LOCATION, PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME, PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME, PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE, PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS, PLAN_ORDER_DESCRIPTION.UPDATE_CODE, PLAN_ORDER_DESCRIPTION.ORDER_STATUS, PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS, PLAN_ORDER_DESCRIPTION.OFFLOAD, PLAN_ORDER_DESCRIPTION.PROD_ORDER, PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND, PLAN_ORDER_DESCRIPTION.ENFORCEMENT, PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE, PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE, PLAN_ORDER_DESCRIPTION.PARENT_ORDER, PLAN_ORDER_DESCRIPTION.SUPER_ORDER, PLAN_ORDER_DESCRIPTION.PLANNER_CODE, PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY, PLAN_ORDER_DESCRIPTION.PARENT_COUPLING, PLAN_ORDER_DESCRIPTION.SKU, PLAN_ORDER_DESCRIPTION.LOCATION, PLAN_ORDER_DESCRIPTION.FAMILY, PLAN_ORDER_DESCRIPTION.STYLE, PLAN_ORDER_DESCRIPTION.COLOR, PLAN_ORDER_DESCRIPTION.ATTRIBUTE, PLAN_ORDER_DESCRIPTION.ORDER_SIZE, PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY, PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY, PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY, PLAN_ORDER_DESCRIPTION.DEMAND_TYPE, PLAN_ORDER_DESCRIPTION.WINDOW_START, PLAN_ORDER_DESCRIPTION.WINDOW_END, PLAN_ORDER_DESCRIPTION.SCHEDULED_START, PLAN_ORDER_DESCRIPTION.SCHEDULED_END, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START, PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END, PLAN_ORDER_DESCRIPTION.PRIORITY, PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR, PLAN_ORDER_DESCRIPTION.NOTE, PLAN_ORDER_DESCRIPTION.VENDOR_NO, PLAN_ORDER_DESCRIPTION.SCRAP_QTY, PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY, PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY, PLAN_ORDER_DESCRIPTION.ATP_DATE_IND, PLAN_ORDER_DESCRIPTION.BACKFILL_IND, PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD, PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO, PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD, PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD, PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD, PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD, PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO, PLAN_ORDER_DESCRIPTION.SELLING_SKU, PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD, PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN, PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO, PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC, PLAN_ORDER_DESCRIPTION.LW_COMPANY, PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
SCHEDULED_START / 1440 + 33231 AS "SewWeek",
SCHEDULED_END / 1440 + 33231 AS "DCWeek", ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC, ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC
FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW, AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD and PLAN_ORDER_DESCRIPTION.PATH_ID = 'C9'

SELECT DISTINCT PLAN_ORDER_DESCRIPTION.PRIME_LOCATION
FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW, AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
WHERE PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD and ISS_CAP_ALLOC_XREF_VIEW.sew_Alloc = 'WM_G20'



SELECT PLAN_ORDER_DESCRIPTION.ORDER_VERSION, 
       PLAN_ORDER_DESCRIPTION.ORDER_LABEL, 
       PLAN_ORDER_DESCRIPTION.ORDER_ID, 
       PLAN_ORDER_DESCRIPTION.PATH_ID, 
       PLAN_ORDER_DESCRIPTION.BOM_ID, 
       PLAN_ORDER_DESCRIPTION.ROUTE_ID, 
       PLAN_ORDER_DESCRIPTION.PRIME_LOCATION, 
       PLAN_ORDER_DESCRIPTION.LOCK_LEAD_TIME, 
       PLAN_ORDER_DESCRIPTION.RELEASE_LEAD_TIME, 
       PLAN_ORDER_DESCRIPTION.MAKE_BUY_CODE, 
       PLAN_ORDER_DESCRIPTION.PRODUCTION_STATUS, 
       PLAN_ORDER_DESCRIPTION.UPDATE_CODE, 
       PLAN_ORDER_DESCRIPTION.ORDER_STATUS, 
       PLAN_ORDER_DESCRIPTION.ACTUALS_STATUS, 
       PLAN_ORDER_DESCRIPTION.OFFLOAD, 
       PLAN_ORDER_DESCRIPTION.PROD_ORDER, 
       PLAN_ORDER_DESCRIPTION.PROD_ORDER_IND, 
       PLAN_ORDER_DESCRIPTION.ENFORCEMENT, 
       PLAN_ORDER_DESCRIPTION.ALLOCATION_OVERRIDE, 
       PLAN_ORDER_DESCRIPTION.MATERIAL_TYPE, 
       PLAN_ORDER_DESCRIPTION.PARENT_ORDER, 
       PLAN_ORDER_DESCRIPTION.SUPER_ORDER, 
       PLAN_ORDER_DESCRIPTION.PLANNER_CODE, 
       PLAN_ORDER_DESCRIPTION.PARENT_ACTIVITY, 
       PLAN_ORDER_DESCRIPTION.PARENT_COUPLING, 
       PLAN_ORDER_DESCRIPTION.SKU, 
       PLAN_ORDER_DESCRIPTION.LOCATION, 
       PLAN_ORDER_DESCRIPTION.FAMILY, 
       PLAN_ORDER_DESCRIPTION.STYLE, 
       PLAN_ORDER_DESCRIPTION.COLOR, 
       PLAN_ORDER_DESCRIPTION.ATTRIBUTE, 
       PLAN_ORDER_DESCRIPTION.ORDER_SIZE, 
       PLAN_ORDER_DESCRIPTION.REMAINING_QUANTITY, 
       PLAN_ORDER_DESCRIPTION.PARITIAL_QUANTITY, 
       PLAN_ORDER_DESCRIPTION.ORIG_QUANTITY, 
       PLAN_ORDER_DESCRIPTION.DEMAND_TYPE, 
       PLAN_ORDER_DESCRIPTION.WINDOW_START, 
       PLAN_ORDER_DESCRIPTION.WINDOW_END, 
       PLAN_ORDER_DESCRIPTION.SCHEDULED_START, 
       PLAN_ORDER_DESCRIPTION.SCHEDULED_END, 
       PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_START, 
       PLAN_ORDER_DESCRIPTION.ORIG_SCHEDULED_END, 
       PLAN_ORDER_DESCRIPTION.PRIORITY, 
       PLAN_ORDER_DESCRIPTION.SCRAP_FACTOR, 
       PLAN_ORDER_DESCRIPTION.NOTE, 
       PLAN_ORDER_DESCRIPTION.VENDOR_NO, 
       PLAN_ORDER_DESCRIPTION.SCRAP_QTY, 
       PLAN_ORDER_DESCRIPTION.NET_ORDER_QTY, 
       PLAN_ORDER_DESCRIPTION.CURR_ORDER_QTY, 
       PLAN_ORDER_DESCRIPTION.ATP_DATE_IND, 
       PLAN_ORDER_DESCRIPTION.BACKFILL_IND, 
       PLAN_ORDER_DESCRIPTION.ORDER_SOURCE_CD, 
       PLAN_ORDER_DESCRIPTION.ISS_ORDER_NO, 
       PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD, 
       PLAN_ORDER_DESCRIPTION.SELLING_COLOR_CD, 
       PLAN_ORDER_DESCRIPTION.SELLING_ATTRIBUTE_CD, 
       PLAN_ORDER_DESCRIPTION.SELLING_SIZE_CD, 
       PLAN_ORDER_DESCRIPTION.MFG_REVISION_NO, 
       PLAN_ORDER_DESCRIPTION.SELLING_SKU, 
       PLAN_ORDER_DESCRIPTION.SCHEDULE_METHOD, 
       PLAN_ORDER_DESCRIPTION.SCHEDULE_RUN, 
       PLAN_ORDER_DESCRIPTION.LW_VENDOR_NO, 
       PLAN_ORDER_DESCRIPTION.LW_VENDOR_LOC, 
       PLAN_ORDER_DESCRIPTION.LW_COMPANY, 
       PLAN_ORDER_DESCRIPTION.ADEXA_PLAN_DATE,
       SCHEDULED_START / 1440 + 33231 AS "SewWeek",
       SCHEDULED_END / 1440 + 33231 AS "DCWeek", 
       ISS_CAP_ALLOC_XREF_VIEW.CUT_ALLOC, 
       ISS_CAP_ALLOC_XREF_VIEW.SEW_ALLOC, 
       ISS_CAP_ALLOC_XREF_VIEW.SRC_ALLOC
FROM OPRSQL.ISS_CAP_ALLOC_XREF_VIEW ISS_CAP_ALLOC_XREF_VIEW
JOIN AVYX.PLAN_ORDER_DESCRIPTION PLAN_ORDER_DESCRIPTION
  ON PLAN_ORDER_DESCRIPTION.SELLING_STYLE_CD = ISS_CAP_ALLOC_XREF_VIEW.STYLE_CD
WHERE PLAN_ORDER_DESCRIPTION.SEW_ALLOC = 'WM_G20';

SELECT *
FROM da.INVENTORY_DAILY inventory
WHERE STYLE = 'PW43AS'

SELECT *
FROM da.INVENTORY_BALANCE ib 
WHERE STYLE = 'PW43AS'


