SELECT PATH_RANKING.STYLE, PATH_RANKING.COLOR, PATH_RANKING.ATTRIBUTE_CD, PATH_RANKING.SIZE_CD, PATH_RANKING.DEMAND_LOC, PATH_RANKING.MFG_PATH_ID, PATH_RANKING.MFG_STYLE_CD, PATH_RANKING.MFG_COLOR_CD, PATH_RANKING.MFG_ATTRIBUTE_CD, PATH_RANKING.MFG_SIZE_CD, PATH_RANKING.PATH_RANKING_NO, PATH_RANKING.CREATE_DATE, PATH_RANKING.UPDATE_DATE, PATH_RANKING.USER_ID, PATH_RANKING.CUT_PART_PATH_ID, PATH_RANKING.FINISHED_FABRIC_PATH_ID, PATH_RANKING.GREIGE_CLOTH_PATH_ID, PATH_RANKING.REVISION_NO
FROM DA.PATH_RANKING PATH_RANKING
WHERE PATH_RANKING.STYLE LIKE 'B74P10%'

SELECT DPR_CUMULATIVE_LEADTIME.CORP_BUSINESS_UNIT, DPR_CUMULATIVE_LEADTIME.STYLE_CD, DPR_CUMULATIVE_LEADTIME.COLOR_CD, DPR_CUMULATIVE_LEADTIME.CUMULATIVE_LEADTIME, DPR_CUMULATIVE_LEADTIME.RECEIPT_PERIOD, DPR_CUMULATIVE_LEADTIME.USER_ID, DPR_CUMULATIVE_LEADTIME.CREATE_DATE, DPR_CUMULATIVE_LEADTIME.UPDATE_DATE
FROM DA.DPR_CUMULATIVE_LEADTIME DPR_CUMULATIVE_LEADTIME
WHERE DPR_CUMULATIVE_LEADTIME.STYLE_CD LIKE 'DF%'

SELECT DPR_CUMULATIVE_LEADTIME.CORP_BUSINESS_UNIT, DPR_CUMULATIVE_LEADTIME.STYLE_CD, DPR_CUMULATIVE_LEADTIME.COLOR_CD, DPR_CUMULATIVE_LEADTIME.CUMULATIVE_LEADTIME, DPR_CUMULATIVE_LEADTIME.RECEIPT_PERIOD, DPR_CUMULATIVE_LEADTIME.USER_ID, DPR_CUMULATIVE_LEADTIME.CREATE_DATE, DPR_CUMULATIVE_LEADTIME.UPDATE_DATE
FROM DA.DPR_CUMULATIVE_LEADTIME DPR_CUMULATIVE_LEADTIME
WHERE DPR_CUMULATIVE_LEADTIME.STYLE_CD = 'DF3488'



SELECT *
FROM DA.STYLE STYLE
WHERE STYLE.STYLE_CD in ('B74P10','40760')

SELECT *
FROM DA.CORP_DIVISION cd 


SELECT *
FROM DA.SKU SKU
WHERE SKU.STYLE_CD = 'B74P10'

SELECT *
FROM DA.CORP_DIVISION cd 

SELECT 
    STYLE.style_cd, STYLE.CORP_DIVISION_CD,
    cd.corp_business_unit
FROM 
    DA.STYLE STYLE
JOIN 
    DA.CORP_DIVISION cd
    ON STYLE.corp_division_cd = cd.corp_division_cd
WHERE
    STYLE.corp_division_cd IN ('91','87','90','77','30','33','OP','92','ON','89','OR','88','OA','71','OR','SC');
