 SELECT FORMAT(WEEK, 'yyyy-MM-dd') as WEEK,
       MEGAWORKCENTERCODE AS MEGA_WORKCENTER,
       ROUND(SUM(CALENDARIZEDDOZENS),2)        AS DZ,
       PLANTCODE AS PLANT_CD,
       WORKCENTERCODE AS WORKCENTER,
       FINANCIALSEGMENT AS FINANCIALSEGMENT
FROM SEWMODEL.DBO.VPRODUCTIONSUMMARYWITHIRRACTUALS AS C
WHERE OPERATIONCODE = 'SEW'
GROUP BY WEEK, MEGAWORKCENTERCODE, PLANTCODE, WORKCENTERCODE,
         FINANCIALSEGMENT
 
SELECT *
FROM FinancialSegmentCodes fsc 

Select *
FROM SEWMODEL.DBO.VPRODUCTIONSUMMARYWITHIRRACTUALS AS C
WHERE OPERATIONCODE = 'SEW'
GROUP BY WEEK, MEGAWORKCENTERCODE, PLANTCODE, WORKCENTERCODE,
         FINANCIALSEGMENT
         
         
Select *
FROM SEWMODEL.DBO.ProductionSummaryWithIrrActualsTable pswiat
where style = 'US4693'
