Original --- Safety Stock

WITH F_MP AS (SELECT DISTINCT MFG_PATH_ID,
                              PATH_RANKING_NO,
                              DEMAND_LOC,
                              STYLE,
                              ROW_NUMBER() OVER (PARTITION BY DEMAND_LOC, STYLE ORDER BY PATH_RANKING_NO) AS RN
              FROM DA.PATH_RANKING@P_PROD1.WORLD
              GROUP BY MFG_PATH_ID, DEMAND_LOC, STYLE, PATH_RANKING_NO
              ORDER BY MFG_PATH_ID)
SELECT STYLE_CD,
       COLOR_CD,
       ATTRIBUTE_CD,
       SIZE_CD,
       FM.DEMAND_LOC                                             AS DC,
       F.WEEK_BEGIN_DATE,
       ROUND(COALESCE(SUM(I.QUANTITY * P.PACK_SIZE) / 12, 0), 2) AS TOTAL_SAFETY_STOCK
FROM IBP_DEMAND I
         LEFT JOIN (SELECT DISTINCT PRIMARY_GROWTH_TEAM, PRODUCT_ID, PACK_SIZE
                    FROM IBP_PRODUCT
                    WHERE PUT_UP_CODE = '000') P ON I.PRODUCT_ID = P.PRODUCT_ID
         INNER JOIN (SELECT DISTINCT * FROM F_MP WHERE RN = 1) FM ON I.STYLE_CD = FM.STYLE
         LEFT JOIN HBI_FISCAL_CALENDAR F ON F.CALENDAR_DATE = I.SHIPMENT_DUE_DATE
WHERE KEY_FIGURE_NAME = 'RECOMMENDEDSAFETYSTOCK' AND Style_CD IN ('SCBBA5','2135')
GROUP BY STYLE_CD, COLOR_CD, ATTRIBUTE_CD, SIZE_CD, FM.DEMAND_LOC, F.WEEK_BEGIN_DATE



TEST1 --- specify SS DATE AND show ALL SKU detail

WITH F_MP AS (
    SELECT DISTINCT MFG_PATH_ID,
                    PATH_RANKING_NO,
                    DEMAND_LOC,
                    STYLE,
                    ROW_NUMBER() OVER (PARTITION BY DEMAND_LOC, STYLE ORDER BY PATH_RANKING_NO) AS RN
    FROM DA.PATH_RANKING@P_PROD1.WORLD
    GROUP BY MFG_PATH_ID, DEMAND_LOC, STYLE, PATH_RANKING_NO
    ORDER BY MFG_PATH_ID
)
SELECT 
    STYLE_CD,
    COLOR_CD,
    ATTRIBUTE_CD,
    SIZE_CD,
    FM.DEMAND_LOC AS DC,
    F.WEEK_BEGIN_DATE,
    ROUND(COALESCE(SUM(I.QUANTITY * P.PACK_SIZE) / 12, 0), 2) AS TOTAL_SAFETY_STOCK
FROM IBP_DEMAND I
LEFT JOIN (
    SELECT DISTINCT PRIMARY_GROWTH_TEAM, PRODUCT_ID, PACK_SIZE
    FROM IBP_PRODUCT
    WHERE PUT_UP_CODE = '000'
) P ON I.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN (
    SELECT DISTINCT * FROM F_MP WHERE RN = 1
) FM ON I.STYLE_CD = FM.STYLE
LEFT JOIN HBI_FISCAL_CALENDAR F ON F.CALENDAR_DATE = I.SHIPMENT_DUE_DATE
WHERE KEY_FIGURE_NAME = 'RECOMMENDEDSAFETYSTOCK' 
  AND Style_CD IN ('225209','2135')
  AND F.WEEK_BEGIN_DATE IN (DATE '2025-11-09', DATE '2025-11-16') -- <---- filter added here
GROUP BY STYLE_CD, COLOR_CD, ATTRIBUTE_CD, SIZE_CD, FM.DEMAND_LOC, F.WEEK_BEGIN_DATE


TEST2 --- specify SS DATE AND collapse TO STYLE code only

WITH F_MP AS (
    SELECT DISTINCT MFG_PATH_ID,
                    PATH_RANKING_NO,
                    DEMAND_LOC,
                    STYLE,
                    ROW_NUMBER() OVER (PARTITION BY DEMAND_LOC, STYLE ORDER BY PATH_RANKING_NO) AS RN
    FROM DA.PATH_RANKING@P_PROD1.WORLD
    GROUP BY MFG_PATH_ID, DEMAND_LOC, STYLE, PATH_RANKING_NO
    ORDER BY MFG_PATH_ID
)
SELECT 
    STYLE_CD,
    F.WEEK_BEGIN_DATE,
    ROUND(COALESCE(SUM(I.QUANTITY * P.PACK_SIZE) / 12, 0), 2) AS TOTAL_SAFETY_STOCK
FROM IBP_DEMAND I
LEFT JOIN (
    SELECT DISTINCT PRIMARY_GROWTH_TEAM, PRODUCT_ID, PACK_SIZE
    FROM IBP_PRODUCT
    WHERE PUT_UP_CODE = '000'
) P ON I.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN (
    SELECT DISTINCT * FROM F_MP WHERE RN = 1
) FM ON I.STYLE_CD = FM.STYLE
LEFT JOIN HBI_FISCAL_CALENDAR F ON F.CALENDAR_DATE = I.SHIPMENT_DUE_DATE
WHERE KEY_FIGURE_NAME = 'RECOMMENDEDSAFETYSTOCK' 
  AND Style_CD IN ('225209','2135')
  AND F.WEEK_BEGIN_DATE IN (DATE '2025-01-26', DATE '2025-05-04', DATE '2025-05-25', DATE '2025-09-28') -- <---- filter added here
GROUP BY STYLE_CD, FM.DEMAND_LOC, F.WEEK_BEGIN_DATE



