SELECT M.STYLE_CD, M.COLOR_CD, M.ATTRIBUTE_CD, M.SIZE_CD, M.MFG_PATH_ID, M.REVISION_NO, M.ORDER_MINIMUM, M.A_ITEM_ORD_INCR
FROM DA.MFG_PATH_CHP M
WHERE M.MFG_PATH_ID = '93'
ORDER BY M.STYLE_CD, M.COLOR_CD, M.SIZE_CD

SELECT STYLE_CD, AVG(FROZEN_TOTAL_COST) AS FOB
FROM DA.FG_XFER_PRICE_COST_ELEMENTS WHERE STYLE_CD IN 
(
'MHG565',
'MHG565',
'MHW199',
'MHW507'
)
GROUP BY STYLE_CD

SELECT STYLE_CD, AVG(MTRL_COST_AMT) AS STD_COST  FROM DA.CORP_STD_COST WHERE COST_TYPE_CD ='P' AND TIMEFRAME_CD = 'F' AND STYLE_CD IN 
(
'AU1127',
 
'BS2270'
)
GROUP BY STYLE_CD 
